### PR TITLE
fix(syncing): refactor error checking for pbft block syncing

### LINKED ISSUE #759: Inconsistent summary info
### Description
Status is inconsistent, once is printing actively syncing, then it prints synced and then again syncing ...

##### Node version

develop

### Actual behaviour

```
2021-05-15 10:58:53.223093 SUMMARY SILENT STATUS: GOOD. ACTIVELY SYNCING
2021-05-15 10:59:13.815418 SUMMARY INFO Connected to 2 peers
2021-05-15 10:59:13.815505 SUMMARY INFO Syncing for 59 seconds, 68% synced
2021-05-15 10:59:13.815562 SUMMARY INFO Currently syncing from node ##009f72d5…
2021-05-15 10:59:13.815609 SUMMARY INFO Max peer PBFT chain size:      7122 (peer ##009f72d5…)
2021-05-15 10:59:13.815658 SUMMARY INFO Max peer PBFT consensus round: 12271 (peer ##009f72d5…)
2021-05-15 10:59:13.815706 SUMMARY INFO Max peer DAG level:            23583 (peer ##009f72d5…)
2021-05-15 10:59:13.815756 SUMMARY INFO In the last 19 seconds...
2021-05-15 10:59:13.815809 SUMMARY INFO PBFT sync period progress:     40
2021-05-15 10:59:13.815858 SUMMARY INFO PBFT chain blocks added:       40
2021-05-15 10:59:13.815909 SUMMARY INFO PBFT rounds advanced:          0
2021-05-15 10:59:13.815957 SUMMARY INFO DAG level growth:              137
2021-05-15 10:59:13.816008 SUMMARY INFO ##################################
2021-05-15 10:59:13.816057 SUMMARY SILENT STATUS: GOOD. ACTIVELY SYNCING
2021-05-15 10:59:33.796199 SUMMARY INFO Connected to 2 peers
2021-05-15 10:59:33.796292 SUMMARY INFO In sync since launch for 30% of the time
2021-05-15 10:59:33.796338 SUMMARY INFO Queued unverified transaction: 0
2021-05-15 10:59:33.796391 SUMMARY INFO Queued verified transaction:   32107
2021-05-15 10:59:33.796435 SUMMARY INFO Max DAG block level in DAG:    14102
2021-05-15 10:59:33.796479 SUMMARY INFO Max DAG block level in queue:  14138
2021-05-15 10:59:33.796527 SUMMARY INFO PBFT chain size:               4970
2021-05-15 10:59:33.796578 SUMMARY INFO Current PBFT round:            5290
2021-05-15 10:59:33.796632 SUMMARY INFO DPOS total votes count:        3
2021-05-15 10:59:33.796666 SUMMARY INFO PBFT consensus 2t+1 threshold: 3
2021-05-15 10:59:33.796703 SUMMARY INFO Node elligible vote count:     0
2021-05-15 10:59:33.796736 SUMMARY INFO In the last 19 seconds...
2021-05-15 10:59:33.796773 SUMMARY INFO PBFT chain blocks added:       60
2021-05-15 10:59:33.796804 SUMMARY INFO PBFT rounds advanced:          0
2021-05-15 10:59:33.796840 SUMMARY INFO DAG level growth:              186
2021-05-15 10:59:33.796871 SUMMARY INFO ##################################
2021-05-15 10:59:33.796899 SUMMARY SILENT STATUS: GOOD. NODE SYNCED
2021-05-15 10:59:53.777009 SUMMARY INFO Connected to 2 peers
2021-05-15 10:59:53.777130 SUMMARY INFO Syncing for 19 seconds, 70% synced
2021-05-15 10:59:53.777175 SUMMARY INFO Currently syncing from node ##009f72d5…
2021-05-15 10:59:53.777214 SUMMARY INFO Max peer PBFT chain size:      7122 (peer ##009f72d5…)
2021-05-15 10:59:53.777256 SUMMARY INFO Max peer PBFT consensus round: 12271 (peer ##009f72d5…)
2021-05-15 10:59:53.777303 SUMMARY INFO Max peer DAG level:            23583 (peer ##009f72d5…)
2021-05-15 10:59:53.777358 SUMMARY INFO In the last 19 seconds...
2021-05-15 10:59:53.777406 SUMMARY INFO PBFT sync period progress:     70
2021-05-15 10:59:53.777443 SUMMARY INFO PBFT chain blocks added:       71
2021-05-15 10:59:53.777496 SUMMARY INFO PBFT rounds advanced:          0
2021-05-15 10:59:53.777548 SUMMARY INFO DAG level growth:              221
2021-05-15 10:59:53.777594 SUMMARY INFO ##################################
2021-05-15 10:59:53.777639 SUMMARY SILENT STATUS: GOOD. ACTIVELY SYNCING
```

### PR DESCRIPTION
**Pull request by justinsnapp**
## Purpose

The current logic for checking if a pbft block + certs that is sent over the network is valid doesn't seem to hold up.

## Related Github issues

Fixes #759 

## Testing

_I tested it against the devnet as follows and syncing is continuous without stopping..._

```
docker login -u _token -p "$(gcloud auth print-access-token)" https://gcr.io
docker pull gcr.io/jovial-meridian-249123/taraxa-node:pr-769-build-1
docker run --rm --name taraxa-devnet gcr.io/jovial-meridian-249123/taraxa-node:pr-761-build-1 join devnet
```

### CODE REVIEW

File: src/network/taraxa_capability.cpp [hunk 1]
```diff
@@ -570,14 +570,29 @@ void TaraxaCapability::interpretCapabilityPacketImpl(NodeID const &_nodeID, unsi
...
-        if (pbft_sync_period + 1 != pbft_blk_and_votes.pbft_blk->getPeriod()) {
-          LOG(log_er_pbft_sync_) << "PBFT SYNC ERROR, UNEXPECTED PBFT BLOCK HEIGHT: "
-                                 << pbft_blk_and_votes.pbft_blk->getPeriod()
-                                 << ", has synced period: " << pbft_sync_period
-                                 << ", PBFT chain size: " << pbft_chain_->getPbftChainSize()
-                                 << ", synced queue size : " << pbft_chain_->pbftSyncedQueueSize();
-          syncing_ = false;
-          return;
+        if (pbft_chain_->isKnownPbftBlockForSyncing(pbft_blk_hash)) {
+          // This is ok I gues...?
```
Comment (gaoqi8649) [inline src/network/taraxa_capability.cpp:574]: I think here should:
return;

**Review by MatusKysel — APPROVED** [review]

**Comment by MatusKysel** [comment]
This fixes #759 for me. Thanks!

**Review by JakubFornadel — APPROVED** [review]

File: src/network/taraxa_capability.cpp (hunk 1 above)
Comment (justinsnapp) [reply src/network/taraxa_capability.cpp]: OK.  Agree.
